kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.089159
    roll: 0
    pitch: 0
    yaw: 0
  upper_arm:
    x: 0
    y: 0.13585
    z: 0
    roll: 0
    pitch: 1.570796327
    yaw: 0
  forearm:
    x: 0
    y: -0.1197
    z: 0.42500
    roll: 0
    pitch: 0
    yaw: 0
  wrist_1:
    x: 0
    y: 0
    z: 0.39225
    roll: 0
    pitch: 1.570796327
    yaw: 0
  wrist_2:
    x: 0
    y: 0.10915
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  wrist_3:
    x: 0
    y: 0
    z: 0.09465
    roll: 0
    pitch: 0
    yaw: 0
  hash: calib_209549117540498681