<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="robot" >
  <xacro:property name="prefix" value="ur5_"/>
  <xacro:property name="wheel_radius" value="0.1651" />
  <xacro:property name="wheel_vertical_offset" value="0.03282" />
  <xacro:property name="M_PI" value="3.14159"/>

  <link name="world"/>

  <link name="floor">
    <visual>
        <origin xyz="0 0 -${wheel_radius - wheel_vertical_offset/2}" rpy="0 0 0" />
        <geometry>
          <box size="2 2 0.00005"/>
        </geometry>
        <material name="Floor">
          <color rgba="0.72 0.80 0.97 0.7"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 -${wheel_radius - wheel_vertical_offset/2}" rpy="0 0 0" />
        <geometry>
          <box size="1 1 0.05"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -${wheel_radius - wheel_vertical_offset/2}" rpy="0 0 0" />
        <geometry>
          <box size="1 1 0.05"/>
        </geometry>
      </collision>
  </link>

  <!-- common stuff -->
  <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro" />

  <!-- ur5 -->
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />

  <!-- arm -->
  <xacro:ur5_robot prefix="${prefix}" joint_limited="false"/>

  <!-- robotiq 85 -->
  <xacro:include filename="$(find robotiq_85_description)/urdf/robotiq_85_gripper.urdf.xacro" />

  <!-- gripper -->
  <xacro:robotiq_85_gripper prefix="" parent="${prefix}ee_link" >
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_85_gripper>

  <!-- husky -->
  <xacro:include filename="$(find ur5_husky_main)/urdf/robot/husky.xacro" />
  <xacro:robot_husky />

  <joint name="floor_to_world" type="fixed">
    <parent link="world"/>
    <child link="floor"/>
    <!-- не трогать xyz и rpy, иначе не считает траекторию! -->
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="base_link_to_floor" type="fixed">
    <parent link="floor"/>
    <child link="base_link"/>
    <!-- не трогать xyz и rpy, иначе не считает траекторию! -->
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="ur5_to_base_link" type="fixed">
    <parent link="top_plate_link"/>
    <child link="${prefix}base_link"/>
    <origin xyz="0.25 0.0 0.0" rpy="0 0 -${M_PI/2}"/>
  </joint>

</robot>
